### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [izuzanak/yapgen#1]
I would like to point out that identifiers like “[`__BASIC_H`](https://github.com/izuzanak/yapgen/blob/fb67dce4d45dc846b92d302c593939555f711264/yapgen/header_files/basic.h#L2 "Update candidate")” and “[`__PARSER_CODE_H`](https://github.com/izuzanak/yapgen/blob/0ba3487edba46568b980ab085e5cc6e2a9808134/yapgen/header_files/parser_code.h#L2 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by izuzanak** [comment]
All header quards were prefixed by YAPGEN_: 2bc2a33cbec0c71216435fb9d4a2312b95bad9cb

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/izuzanak/yapgen/commit/2bc2a33cbec0c71216435fb9d4a2312b95bad9cb "Renaming of include guards").
